export const STOCK_VOCABULARY = [
  "delv(?:e|es|ed|ing)",
  "tapestry",
  "testament",
  "pivotal",
  "intricate(?:ly)?",
  "intricacies",
  "multifaceted",
  "realm",
  "underscor(?:e|es|ed|ing)",
  "showcas(?:e|es|ed|ing)",
  "foster(?:s|ed|ing)?",
  "bolster(?:s|ed|ing)?",
  "garner(?:s|ed|ing)?",
  "leverag(?:e|es|ed|ing)",
  "seamless(?:ly)?",
  "robust",
  "nuanced?",
  "meticulous(?:ly)?",
  "embark(?:s|ed|ing)?",
  "elevat(?:e|es|ed|ing)",
  "harness(?:es|ed|ing)?",
  "ever-(?:evolving|changing)",
  "game-changer",
  "paramount",
  "holistic",
  "synerg(?:y|ies)",
  "crucial",
  "comprehensive",
  "transformative",
  "unwavering",
  "commendable",
  "invaluable",
  "streamlin(?:e|es|ed|ing)",
  "empower(?:s|ed|ing)?",
  "resonat(?:e|es|ed|ing)",
  "navigat(?:e|es|ing) the",
  "unlock(?:s|ed|ing)? the",
  "dive (?:deep|into)",
  "deep dive",
  "in the realm of",
  "a myriad of",
  "myriad",
  "plethora",
  "noteworthy",
  "captivat(?:e|es|ed|ing)",
  "enhanc(?:e|es|ed|ing)",
  "ensur(?:e|es|ed|ing)",
]

export const COPULA_SUBSTITUTES = [
  "serves? as",
  "served as",
  "serving as",
  "stands? as",
  "stood as",
  "acts? as",
  "functions? as",
  "boasts?",
  "boasting",
  "features an?",
  "represents an?",
  "marks an?",
]

export const FILLER_PHRASES = [
  "it(?:'s| is) (?:important|worth|crucial|essential) (?:to note|noting|to remember|to consider|to understand)",
  "it should be noted",
  "in today's (?:fast-paced|digital|modern|ever-changing) (?:world|age|landscape|era)",
  "when it comes to",
  "at the end of the day",
  "in order to",
  "the fact that",
  "needless to say",
  "it goes without saying",
  "in terms of",
  "with that (?:said|in mind)",
  "that being said",
  "all things considered",
  "a wide (?:range|array|variety) of",
  "plays? a (?:key|vital|crucial|significant|important) role",
]

export const CHATBOT_ARTIFACTS = [
  "certainly!?",
  "absolutely!",
  "great question",
  "i hope this helps",
  "hope this helps",
  "let me know if(?: you)?",
  "feel free to",
  "i'd be happy to",
  "happy to help",
  "as an ai",
  "here's (?:a|an|the) (?:breakdown|overview|summary)",
  "here are (?:some|a few)",
  "in this (?:article|post|guide|blog post), (?:we|i) will",
  "let's (?:dive|explore|take a closer look|break (?:it|this) down)",
  "i hope you (?:found|find)",
  "thank you for (?:reading|your question)",
  "you might (?:want|also want) to",
]

export const PROMOTIONAL_ADJECTIVES = [
  "breathtaking",
  "stunning",
  "nestled",
  "vibrant",
  "renowned",
  "world-class",
  "unparalleled",
  "cutting-edge",
  "must-visit",
  "must-see",
  "awe-inspiring",
  "picturesque",
  "bustling",
  "thriving",
  "rich (?:cultural )?(?:heritage|history|tapestry)",
  "state-of-the-art",
  "unrivaled",
  "exquisite",
  "iconic",
  "enchanting",
  "unforgettable",
  "hidden gem",
  "best-in-class",
  "next-level",
  "revolutioni[sz](?:e|es|ed|ing)",
  "groundbreaking",
  "innovative",
]

export const METAPHOR_NOUNS = [
  "tapestr(?:y|ies)",
  "landscape",
  "realm",
  "journey",
  "symphony",
  "beacon",
  "cornerstone",
  "testament",
  "mosaic",
  "fabric of",
  "crucible",
  "labyrinth",
  "melting pot",
  "ecosystem",
  "treasure trove",
  "kaleidoscope",
  "linchpin",
  "bedrock",
  "north star",
  "double-edged sword",
  "uncharted (?:waters|territory)",
]

export const CUTOFF_DISCLAIMERS = [
  "as of my (?:last|latest) (?:update|knowledge update|training)",
  "as of my knowledge cutoff",
  "my knowledge cutoff",
  "while specific details are (?:limited|scarce)",
  "i (?:don't|do not) have (?:access|real-time)",
  "i (?:cannot|can't) browse",
  "based on (?:available|my) (?:information|training data)",
  "up to my last",
  "as an ai language model",
]

export const SIGNIFICANCE_INFLATION = [
  "plays? a (?:pivotal|crucial|vital|key|significant|central) role",
  "stands? as a testament",
  "a testament to",
  "marks? a (?:significant|pivotal|major) (?:shift|moment|milestone|turning point)",
  "enduring (?:legacy|impact)",
  "lasting (?:legacy|impact)",
  "shaping the future",
  "key turning point",
  "indelible mark",
  "deeply rooted",
  "cannot be overstated",
  "profound(?:ly)? (?:impact|influence|shaped)",
  "rich (?:history|legacy)",
  "pivotal moment",
  "reflects? (?:the|a) broader",
  "setting the stage for",
]

export const VAGUE_ATTRIBUTION = [
  "experts (?:say|believe|argue|suggest|agree|note)",
  "studies (?:show|suggest|have shown|indicate)",
  "research (?:shows|suggests|indicates|has shown)",
  "critics (?:argue|say|contend|have noted)",
  "observers (?:have )?not(?:e|ed)",
  "it is widely (?:believed|accepted|recognized|regarded)",
  "many (?:believe|argue|people believe|experts)",
  "some (?:argue|say|critics|experts|believe)",
  "according to (?:experts|some|many|industry)",
  "widely (?:regarded|considered|recognized) as",
  "has been described as",
  "is often (?:cited|described|regarded|considered)",
]

export const CHALLENGES_ARC = [
  "despite (?:its|these|the|their|such|many|numerous|several) (?:challenges|setbacks|obstacles|hurdles|difficulties)",
  "faces? (?:several|many|numerous|significant) challenges",
  "continues? to (?:thrive|evolve|flourish|grow|inspire)",
  "challenges (?:remain|persist)",
  "not without (?:its|their) (?:challenges|critics|flaws)",
  "while challenges remain",
  "future (?:prospects|outlook)",
  "remains? (?:a|an) (?:vital|important|key|integral)",
]

export const UPBEAT_CONCLUSIONS = [
  "the future (?:looks|is) bright",
  "exciting times (?:ahead|lie ahead)",
  "the possibilities are endless",
  "only time will tell",
  "the sky is the limit",
  "paving the way",
  "bright future",
  "poised (?:to|for)",
  "here to stay",
  "a new era",
  "the journey (?:is|has) just begun",
  "stay tuned",
  "endless possibilities",
  "the best is yet to come",
]

export const BOTH_SIDES = [
  "ultimately,? (?:it|the (?:choice|decision|answer)) (?:depends|comes down|boils down)",
  "there is no one-size-fits-all",
  "no one-size-fits-all",
  "both (?:have|offer) their (?:own )?(?:merits|strengths|pros)",
  "it depends on your (?:specific )?(?:needs|goals|situation)",
  "the right choice (?:depends|will depend)",
  "strik(?:e|es|ing) a balance",
  "weigh(?:ing)? the pros and cons",
  "each has its (?:own )?(?:strengths|advantages|merits)",
]

export const SENTENCE_TRANSITIONS = [
  "moreover",
  "furthermore",
  "additionally",
  "consequently",
  "notably",
  "importantly",
  "ultimately",
  "nevertheless",
  "nonetheless",
  "conversely",
  "subsequently",
  "thus",
  "hence",
  "in addition",
  "as a result",
  "in essence",
  "essentially",
  "overall",
]

export const RECAP_OPENERS = [
  "in summary",
  "in conclusion",
  "to sum up",
  "to summarize",
  "overall",
  "all in all",
  "in short",
  "as mentioned",
  "as discussed",
  "as noted",
  "as we've seen",
  "as highlighted",
  "in essence",
  "to conclude",
  "ultimately",
]

export const POINTER_OPENERS = [
  "this",
  "these",
  "those",
  "that's why",
  "that is why",
  "here's the thing",
  "here's why",
  "the result\\?",
  "the answer\\?",
  "the catch\\?",
  "the kicker\\?",
  "the bottom line",
  "the takeaway",
  "it's",
]

export const HEDGES = [
  "may",
  "might",
  "could",
  "potentially",
  "possibly",
  "arguably",
  "generally",
  "often",
  "typically",
  "somewhat",
  "perhaps",
  "likely",
  "tends? to",
  "can be",
  "relatively",
  "largely",
]

export const ANALYSIS_PARTICIPLES = [
  "highlighting",
  "underscoring",
  "reflecting",
  "showcasing",
  "emphasizing",
  "emphasising",
  "illustrating",
  "demonstrating",
  "signaling",
  "signalling",
  "symbolizing",
  "contributing to",
  "ensuring",
  "fostering",
  "making it",
  "solidifying",
  "cementing",
  "paving",
  "creating",
  "allowing",
  "enabling",
  "offering",
  "providing",
]

export const IRREGULAR_PARTICIPLES = [
  "built",
  "made",
  "done",
  "given",
  "known",
  "seen",
  "shown",
  "written",
  "taken",
  "held",
  "found",
  "brought",
  "thought",
  "told",
  "left",
  "kept",
  "led",
  "set",
  "sent",
  "paid",
  "won",
  "driven",
  "chosen",
  "drawn",
  "grown",
]

export const REAL_RANGE_STARTS = [
  "\\$?\\d",
  "\\w+day",
  "january",
  "february",
  "march",
  "april",
  "may",
  "june",
  "july",
  "august",
  "september",
  "october",
  "november",
  "december",
  "morning",
  "dawn",
  "start",
  "beginning",
  "top",
  "left",
  "one",
]

export const OPINION_MARKERS = [
  "i think",
  "i believe",
  "i feel",
  "i'd say",
  "imo",
  "imho",
  "honestly",
  "frankly",
  "personally",
  "in my (?:view|opinion|experience)",
  "i guess",
  "i suppose",
  "i love",
  "i hate",
  "i like",
  "i don't like",
  "i'm not sure",
  "to me",
]

export const FIRST_PERSON = new Set([
  "i",
  "me",
  "my",
  "mine",
  "i'm",
  "i've",
  "i'd",
  "i'll",
  "we",
  "our",
  "us",
  "we're",
  "we've",
])

export const NOT_ADVERBS = new Set([
  "only",
  "family",
  "early",
  "daily",
  "likely",
  "reply",
  "apply",
  "supply",
  "italy",
  "july",
  "holy",
  "belly",
  "rally",
  "ally",
  "fly",
  "assembly",
  "anomaly",
  "monopoly",
  "weekly",
  "monthly",
  "yearly",
  "lonely",
  "friendly",
  "lovely",
  "ugly",
  "silly",
  "jelly",
  "bully",
  "curly",
  "hourly",
  "costly",
  "elderly",
  "orderly",
  "scholarly",
  "emily",
  "kelly",
  "billy",
  "sally",
  "molly",
  "lily",
  "hilly",
  "chilly",
])

/** The commonest English function words. Their share of a text says whether it is English at all. */
export const ENGLISH_FUNCTION_WORDS = new Set(
  (
    "the of and to in is it that was for on are as with his her they be this " +
    "from or had by but what were we when your there their which been these " +
    "who will would about into them than then its our you he she have has not"
  ).split(" ")
)
